all: part1 part2

part1: part1.c
	cc -g -Wall -Wextra -pedantic -Wno-unused-function -Wconversion -Wsign-conversion $< -o $@

part2: part2.c
	cc -g -Wall -Wextra -pedantic -Wno-unused-function -Wconversion -Wsign-conversion $< -o $@
